import type { Metadata } from "next";
import "./globals.css";
import { Cuprum } from 'next/font/google'

const inter = Cuprum({
  subsets: ['cyrillic'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={inter.className}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
